version: '3.1'

services:
  db:
    image: leziit00/postgresdb:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    networks:
      - ds-lab
  backend:
    image: leziit00/cds-server:latest
    restart: always
    ports: 
      - 4004:4004
    networks:
      - ds-lab
  # frontend:
  #   image: todo-app
  #   restart: always
  #   ports: 
  #     - 80:5550
  #   networks:
  #     - ds-lab
networks:
  ds-lab:
    driver: bridge