# Use a base image with Node.js pre-installed
FROM node:lts

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose any necessary ports (e.g., if your application runs on port 4005)
EXPOSE 4004

# Define the command to start your application
CMD [ "npm", "start" ]
